"""
ComplyAI Backend - PDF Generator Service

Generates two production-quality PDF documents using ReportLab:
 1. Improved Company Policy PDF (Cover page + formatted legal policy document)
 2. Executive Compliance Audit Report PDF (Cover page + Executive Summary + Gaps + Recommendations + Clause Improvements + Overall Assessment)

Stores generated files in backend/generated_reports/ and returns downloadable URLs.
"""

from __future__ import annotations

import logging
import os
import re
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)

# Target directory for generated PDF reports
BASE_DIR = Path(__file__).resolve().parent.parent
GENERATED_REPORTS_DIR = BASE_DIR / "generated_reports"

# Base URL prefix for serving reports
HOST_URL = os.getenv("API_HOST_URL", "http://127.0.0.1:8000")


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to compute total page numbers ("Page X of Y")
    and render professional headers and footers on every page after the cover.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer(num_pages)
            super().showPage()
        super().save()

    def draw_header_footer(self, page_count: int):
        # Skip header and footer on Cover Page (Page 1)
        if self._pageNumber == 1:
            return

        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Header (Top margin: 0.75 in = 54 pt, Letter height = 11 in = 792 pt)
        header_text = "CONFIDENTIAL — COMPLYAI ENTERPRISE AUDIT REPORT"
        self.drawString(54, 792 - 36, header_text)
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(54, 792 - 42, 612 - 54, 792 - 42)

        # Footer
        self.line(54, 48, 612 - 54, 48)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(612 - 54, 34, page_str)
        self.drawString(54, 34, "Generated by ComplyAI Engine • Legal & Compliance Copilot")
        self.restoreState()


class PolicyNumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas for Improved Policy PDF to draw running header & footer.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer(num_pages)
            super().showPage()
        super().save()

    def draw_header_footer(self, page_count: int):
        if self._pageNumber == 1:
            return

        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#475569"))

        # Header
        self.drawString(54, 792 - 36, "OFFICIAL REVISED POLICY DOCUMENT • COMPLYAI DRAFT")
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(54, 792 - 42, 612 - 54, 792 - 42)

        # Footer
        self.line(54, 48, 612 - 54, 48)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(612 - 54, 34, page_str)
        self.drawString(54, 34, "CONFIDENTIAL & PROPRIETARY — LEGAL COMPLIANCE REWRITE")
        self.restoreState()


def _clean_text_for_pdf(text: str) -> str:
    """Helper to convert basic markdown formatting into ReportLab HTML tags."""
    if not text:
        return ""
    cleaned = str(text)
    cleaned = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", cleaned)
    cleaned = re.sub(r"\*(.*?)\*", r"<i>\1</i>", cleaned)
    cleaned = re.sub(r"`(.*?)`", r"<font name='Courier'>\1</font>", cleaned)
    cleaned = re.sub(r"^#+\s*", "", cleaned)
    return cleaned.strip()


def _get_styles() -> Dict[str, ParagraphStyle]:
    """Build custom ParagraphStyles for document layout."""
    styles = getSampleStyleSheet()

    custom_styles = {
        "Normal": styles["Normal"],
        "CoverTitle": ParagraphStyle(
            "CoverTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=26,
            leading=32,
            textColor=colors.HexColor("#0F172A"),
            alignment=TA_LEFT,
            spaceAfter=10,
        ),
        "CoverSubtitle": ParagraphStyle(
            "CoverSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=13,
            leading=18,
            textColor=colors.HexColor("#475569"),
            alignment=TA_LEFT,
            spaceAfter=24,
        ),
        "SectionHeading": ParagraphStyle(
            "SectionHeading",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=15,
            leading=20,
            textColor=colors.HexColor("#1E3A8A"),
            spaceBefore=18,
            spaceAfter=10,
            keepWithNext=True,
        ),
        "SubSectionHeading": ParagraphStyle(
            "SubSectionHeading",
            parent=styles["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#0F172A"),
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True,
        ),
        "BodyText": ParagraphStyle(
            "BodyTextCustom",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=15,
            textColor=colors.HexColor("#1E293B"),
            alignment=TA_LEFT,
            spaceAfter=8,
        ),
        "LegalBody": ParagraphStyle(
            "LegalBodyText",
            parent=styles["BodyText"],
            fontName="Times-Roman",
            fontSize=10.5,
            leading=16,
            textColor=colors.HexColor("#0F172A"),
            alignment=TA_JUSTIFY,
            spaceAfter=10,
        ),
        "ListItem": ParagraphStyle(
            "ListItemCustom",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#1E293B"),
        ),
        "MetaLabel": ParagraphStyle(
            "MetaLabel",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor("#334155"),
        ),
        "MetaValue": ParagraphStyle(
            "MetaValue",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor("#0F172A"),
        ),
        "ClauseBoxHeader": ParagraphStyle(
            "ClauseBoxHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#1E293B"),
            spaceAfter=4,
        ),
        "ClauseBoxText": ParagraphStyle(
            "ClauseBoxText",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#334155"),
        ),
        "Arrow": ParagraphStyle(
            "Arrow",
            parent=styles["Normal"],
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
            fontSize=8,
            textColor=colors.HexColor("#15803D"),
        ),
    }

    return custom_styles


def generate_improved_policy_pdf(analysis_result: dict, org_data: dict, output_dir: Optional[Path] = None) -> str:
    """
    Generate Document 1: Improved Company Policy PDF.

    Includes a formal Cover Page (Company Name, Industry, Country, State, Date,
    Score, Risk Level, Prepared by ComplyAI) followed by the complete revised policy.
    """
    target_dir = output_dir or GENERATED_REPORTS_DIR
    target_dir.mkdir(parents=True, exist_ok=True)

    file_id = uuid.uuid4().hex[:8]
    filename = f"improved_policy_{file_id}.pdf"
    file_path = target_dir / filename

    styles = _get_styles()
    doc = SimpleDocTemplate(
        str(file_path),
        pagesize=LETTER,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
        title="Improved Company Policy Document",
    )

    company_name = org_data.get("companyName") or org_data.get("company_name") or "Corporate Client"
    industry = org_data.get("industry") or "Enterprise / Commercial"
    country = org_data.get("headquartersCountry") or org_data.get("headquarters_country") or "United States"
    state = org_data.get("state") or "N/A"
    audit_date = datetime.now().strftime("%B %d, %Y")
    score = analysis_result.get("compliance_score", "N/A")
    risk = str(analysis_result.get("risk_level", "Medium")).capitalize()
    revised_policy = analysis_result.get("revised_policy") or analysis_result.get("revised_policy_text") or "No revised policy content generated."

    story = []

    # --- COVER PAGE ---
    story.append(Spacer(1, 40))
    story.append(Paragraph("REVISED COMPANY POLICY", styles["CoverTitle"]))
    story.append(Paragraph("Compliance-Ready Legal & Policy Rewrite Document", styles["CoverSubtitle"]))
    story.append(HRFlowable(width="100%", thickness=3, color=colors.HexColor("#1E3A8A"), spaceAfter=30))

    meta_table_data = [
        [Paragraph("Organization Name:", styles["MetaLabel"]), Paragraph(company_name, styles["MetaValue"])],
        [Paragraph("Industry Sector:", styles["MetaLabel"]), Paragraph(industry, styles["MetaValue"])],
        [Paragraph("Jurisdiction / Location:", styles["MetaLabel"]), Paragraph(f"{state}, {country}", styles["MetaValue"])],
        [Paragraph("Date of Revision:", styles["MetaLabel"]), Paragraph(audit_date, styles["MetaValue"])],
        [Paragraph("Prepared By:", styles["MetaLabel"]), Paragraph("ComplyAI Engine (Compliance Copilot)", styles["MetaValue"])],
        [Paragraph("Compliance Score:", styles["MetaLabel"]), Paragraph(f"<b>{score}%</b>", styles["MetaValue"])],
        [Paragraph("Risk Exposure Level:", styles["MetaLabel"]), Paragraph(f"<b>{risk} Risk</b>", styles["MetaValue"])],
    ]

    meta_table = Table(meta_table_data, colWidths=[2.2 * inch, 4.3 * inch])
    meta_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#F1F5F9")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 12),
                ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ]
        )
    )

    story.append(meta_table)
    story.append(Spacer(1, 40))

    notice_box_data = [
        [
            Paragraph(
                "<b>NOTICE & LEGAL DISCLAIMER:</b> This revised policy document has been automatically "
                "re-engineered by the ComplyAI Engine to align corporate practices with target regulatory "
                "frameworks. All original company information and compliant directives have been preserved. "
                "Formal legal review by authorized counsel is recommended prior to final policy adoption.",
                styles["ClauseBoxText"],
            )
        ]
    ]
    notice_table = Table(notice_box_data, colWidths=[6.5 * inch])
    notice_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EFF6FF")),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#BFDBFE")),
                ("PADDING", (0, 0), (-1, -1), 12),
            ]
        )
    )
    story.append(notice_table)

    story.append(PageBreak())

    # --- POLICY BODY ---
    story.append(Paragraph("OFFICIAL COMPANY POLICY", styles["SectionHeading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=16))

    # Split policy into paragraphs and render with legal typography
    lines = revised_policy.splitlines()
    for line in lines:
        cleaned_line = _clean_text_for_pdf(line)
        if not cleaned_line:
            continue

        # Detect headers
        if cleaned_line.isupper() or re.match(r"^(?:SECTION|ARTICLE|\d+\.\d+)\b", cleaned_line, re.IGNORECASE):
            story.append(Paragraph(cleaned_line, styles["SubSectionHeading"]))
        else:
            story.append(Paragraph(cleaned_line, styles["LegalBody"]))

    doc.build(story, canvasmaker=PolicyNumberedCanvas)
    logger.info("Generated Improved Policy PDF at: %s", file_path)

    return f"{HOST_URL}/generated_reports/{filename}"


def generate_audit_report_pdf(analysis_result: dict, org_data: dict, output_dir: Optional[Path] = None) -> str:
    """
    Generate Document 2: Executive Compliance Audit Report PDF.

    Includes Cover Page, Executive Summary, Score & Risk Table, Missing Requirements,
    Recommendations, Clause Improvements (Original -> Improved -> Reason), Overall Assessment,
    and Next Recommended Actions.
    """
    target_dir = output_dir or GENERATED_REPORTS_DIR
    target_dir.mkdir(parents=True, exist_ok=True)

    file_id = uuid.uuid4().hex[:8]
    filename = f"audit_report_{file_id}.pdf"
    file_path = target_dir / filename

    styles = _get_styles()
    doc = SimpleDocTemplate(
        str(file_path),
        pagesize=LETTER,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
        title="Executive Compliance Audit Report",
    )

    company_name = org_data.get("companyName") or org_data.get("company_name") or "Corporate Client"
    industry = org_data.get("industry") or "Enterprise"
    country = org_data.get("headquartersCountry") or org_data.get("headquarters_country") or "Global"
    frameworks = org_data.get("complianceFrameworks") or org_data.get("compliance_framework") or "General Compliance"
    if isinstance(frameworks, list):
        frameworks = ", ".join(frameworks)

    audit_ref = f"AUD-{uuid.uuid4().hex[:6].upper()}"
    audit_date = datetime.now().strftime("%B %d, %Y — %H:%M UTC")

    score = analysis_result.get("compliance_score", 0)
    risk = str(analysis_result.get("risk_level", "Medium")).capitalize()
    summary = analysis_result.get("summary") or "No executive summary provided."
    missing_requirements = analysis_result.get("missing_requirements") or []
    recommendations = analysis_result.get("recommendations") or []
    improved_clauses = analysis_result.get("improved_clauses") or []

    story = []

    # --- COVER PAGE ---
    story.append(Spacer(1, 40))
    story.append(Paragraph("EXECUTIVE COMPLIANCE AUDIT REPORT", styles["CoverTitle"]))
    story.append(Paragraph("Automated Policy Gap Analysis & Regulatory Remediation Report", styles["CoverSubtitle"]))
    story.append(HRFlowable(width="100%", thickness=3, color=colors.HexColor("#1E3A8A"), spaceAfter=30))

    cover_meta_data = [
        [Paragraph("Target Organization:", styles["MetaLabel"]), Paragraph(company_name, styles["MetaValue"])],
        [Paragraph("Industry Sector:", styles["MetaLabel"]), Paragraph(industry, styles["MetaValue"])],
        [Paragraph("Primary Jurisdiction:", styles["MetaLabel"]), Paragraph(country, styles["MetaValue"])],
        [Paragraph("Compliance Framework:", styles["MetaLabel"]), Paragraph(str(frameworks), styles["MetaValue"])],
        [Paragraph("Audit Reference ID:", styles["MetaLabel"]), Paragraph(f"<code>{audit_ref}</code>", styles["MetaValue"])],
        [Paragraph("Audit Generated:", styles["MetaLabel"]), Paragraph(audit_date, styles["MetaValue"])],
        [Paragraph("Auditing Engine:", styles["MetaLabel"]), Paragraph("ComplyAI Copilot Intelligence v1.0", styles["MetaValue"])],
    ]

    cover_table = Table(cover_meta_data, colWidths=[2.2 * inch, 4.3 * inch])
    cover_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#F1F5F9")),
                ("PADDING", (0, 0), (-1, -1), 9),
            ]
        )
    )
    story.append(cover_table)

    story.append(PageBreak())

    # --- EXECUTIVE SUMMARY ---
    story.append(Paragraph("1. Executive Summary", styles["SectionHeading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=14))

    risk_bg_color = (
        colors.HexColor("#DCFCE7") if risk.lower() == "low"
        else colors.HexColor("#FEF3C7") if risk.lower() == "medium"
        else colors.HexColor("#FEE2E2")
    )
    risk_text_color = (
        colors.HexColor("#15803D") if risk.lower() == "low"
        else colors.HexColor("#B45309") if risk.lower() == "medium"
        else colors.HexColor("#B91C1C")
    )

    score_table_data = [
        [
            Paragraph("<b>Overall Compliance Score</b>", styles["MetaLabel"]),
            Paragraph("<b>Regulatory Risk Level</b>", styles["MetaLabel"]),
        ],
        [
            Paragraph(f"<font size=20 color='#0F172A'><b>{score}%</b></font>", styles["MetaValue"]),
            Paragraph(f"<font size=14 color='{risk_text_color.hexval()}'><b>{risk} Risk</b></font>", styles["MetaValue"]),
        ],
    ]

    score_table = Table(score_table_data, colWidths=[3.25 * inch, 3.25 * inch])
    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F1F5F9")),
                ("BACKGROUND", (1, 0), (1, -1), risk_bg_color),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("PADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )
    story.append(score_table)
    story.append(Spacer(1, 14))

    story.append(Paragraph(_clean_text_for_pdf(summary), styles["BodyText"]))
    story.append(Spacer(1, 16))

    # --- MISSING REQUIREMENTS ---
    story.append(Paragraph("2. Missing Requirements & Regulatory Gaps", styles["SectionHeading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=12))

    if missing_requirements:
        gap_items = []
        for gap in missing_requirements:
            gap_text = _clean_text_for_pdf(str(gap))
            gap_items.append(ListItem(Paragraph(gap_text, styles["ListItem"]), leftIndent=15))
        story.append(ListFlowable(gap_items, bulletType="bullet", start="circle", spaceAfter=14))
    else:
        story.append(Paragraph("No major regulatory gaps identified.", styles["BodyText"]))

    story.append(Spacer(1, 16))

    # --- RECOMMENDATIONS ---
    story.append(Paragraph("3. Remediation Recommendations", styles["SectionHeading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=12))

    if recommendations:
        rec_items = []
        for rec in recommendations:
            rec_text = _clean_text_for_pdf(str(rec))
            rec_items.append(ListItem(Paragraph(rec_text, styles["ListItem"]), leftIndent=15))
        story.append(ListFlowable(rec_items, bulletType="bullet", start="square", spaceAfter=14))
    else:
        story.append(Paragraph("No immediate remediation recommendations specified.", styles["BodyText"]))

    story.append(Spacer(1, 16))

    # --- CLAUSE IMPROVEMENTS ---
    story.append(Paragraph("4. AI Clause Improvements & Amendments", styles["SectionHeading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=14))

    if improved_clauses:
        for idx, clause in enumerate(improved_clauses, 1):
            issue = _clean_text_for_pdf(clause.get("issue") or "Compliance Issue")
            original = _clean_text_for_pdf(clause.get("original") or "N/A")
            improved = _clean_text_for_pdf(clause.get("improved") or "N/A")
            reason = _clean_text_for_pdf(clause.get("reason") or "N/A")

            clause_block_data = [
                [Paragraph(f"<b>AMENDMENT #{idx}: {issue}</b>", styles["ClauseBoxHeader"])],
                [
                    Paragraph(
                        f"<b>Original Clause:</b><br/><font color='#991B1B'>{original}</font>",
                        styles["ClauseBoxText"],
                    )
                ],
                [Paragraph("<b>↓ REVISED CLAUSE AMENDMENT ↓</b>", ParagraphStyle("Arrow", parent=styles["Normal"], alignment=TA_CENTER, fontName="Helvetica-Bold", fontSize=8, textColor=colors.HexColor("#15803D")))],
                [
                    Paragraph(
                        f"<b>Corrected Policy Clause:</b><br/><font color='#166534'><b>{improved}</b></font>",
                        styles["ClauseBoxText"],
                    )
                ],
                [
                    Paragraph(
                        f"<b>Reason for Amendment:</b><br/>{reason}",
                        styles["ClauseBoxText"],
                    )
                ],
            ]

            clause_table = Table(clause_block_data, colWidths=[6.5 * inch])
            clause_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
                        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#FEF2F2")),
                        ("BACKGROUND", (0, 2), (-1, 2), colors.HexColor("#F8FAFC")),
                        ("BACKGROUND", (0, 3), (-1, 3), colors.HexColor("#F0FDF4")),
                        ("BACKGROUND", (0, 4), (-1, 4), colors.HexColor("#EFF6FF")),
                        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
                        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                        ("PADDING", (0, 0), (-1, -1), 8),
                    ]
                )
            )

            story.append(KeepTogether([clause_table, Spacer(1, 14)]))
    else:
        story.append(Paragraph("No clause-level amendments recorded.", styles["BodyText"]))

    story.append(Spacer(1, 16))

    # --- OVERALL ASSESSMENT & CONCLUSION ---
    story.append(Paragraph("5. Overall Assessment & Compliance Readiness", styles["SectionHeading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=12))

    readiness_status = "High Readiness (Audit-Ready)" if score >= 80 else "Moderate Readiness (Action Required)" if score >= 50 else "High Exposure (Immediate Remediation Needed)"

    assessment_text = (
        f"<b>Overall Readiness:</b> {readiness_status}<br/><br/>"
        f"The organization's policy infrastructure currently demonstrates a compliance score of <b>{score}%</b>. "
        f"By implementing the {len(improved_clauses)} clause amendments detailed in Section 4 and fulfilling the "
        f"recommendations outlined in Section 3, the policy will reach full audit readiness under {frameworks} standards."
    )
    story.append(Paragraph(assessment_text, styles["BodyText"]))
    story.append(Spacer(1, 14))

    next_actions_data = [
        ListItem(Paragraph("Distribute the <b>Improved Company Policy</b> document to legal counsel for final validation.", styles["ListItem"])),
        ListItem(Paragraph("Incorporate recommended risk controls into operational procedures.", styles["ListItem"])),
        ListItem(Paragraph("Archive this audit report for compliance evidence and regulatory inquiry.", styles["ListItem"])),
    ]
    story.append(Paragraph("<b>Next Recommended Actions:</b>", styles["SubSectionHeading"]))
    story.append(ListFlowable(next_actions_data, bulletType="bullet", start="check", spaceAfter=14))


    doc.build(story, canvasmaker=NumberedCanvas)
    logger.info("Generated Audit Report PDF at: %s", file_path)

    return f"{HOST_URL}/generated_reports/{filename}"
